### PR TITLE
chore: add github pull request template

### PR DESCRIPTION
**Pull request by will-t-harris**
Figured we should get a copy of this in here as well.

Do we want to change anything about the template? 🤔

### CODE REVIEW

**Review by pfuscoe — APPROVED** [review]
Should we maybe move the Notes section above Visuals? No strong feelings - I've just gotten used to it that way. It might be good to keep the text together since visuals can take up a lot of space.

**Comment by will-t-harris** [comment]
> Should we maybe move the Notes section above Visuals?

Yes, I think this is a good idea 👍

**Review by rmutter — APPROVED** [review]

**Review by emcclosky — APPROVED** [review]

**Comment by jonnyschult** [comment]
Is the project name heading redundant? It seems that the project should be obvious to anyone making/checking a PR.

**Review by jonnyschult — APPROVED** [review]

**Comment by will-t-harris** [comment]
> Is the project name heading redundant? It seems that the project should be obvious to anyone making/checking a PR.

It might be, but I'm not sure what else we'd use as a top-level header (`h1`-equivalent).

**Review by Harry823 — APPROVED** [review]

**Review by Cscharf91 — APPROVED** [review]

**Pull request merged**
